# Numpy Introduction

In [1]:
import numpy as np

In [2]:
np.array([4,5,6,8,8,'hi'])

array(['4', '5', '6', '8', '8', 'hi'], dtype='<U11')

In [3]:
np.array([4,5,6,8,8,10.5])

array([ 4. ,  5. ,  6. ,  8. ,  8. , 10.5])

In [4]:
np.array([4,5,6,8,8,10.5,True])

array([ 4. ,  5. ,  6. ,  8. ,  8. , 10.5,  1. ])

#### Numpy Ways to create array

In [5]:
# First Method
arr_1 = np.array([3,4,6,8,9,7,12])

In [6]:
arr_1

array([ 3,  4,  6,  8,  9,  7, 12])

In [7]:
arr_1[0]

3

In [8]:
arr_1[0:4]

array([3, 4, 6, 8])

In [11]:
# Second Method
# np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
# third method
# np.linspace(1,10)
# np.linspace(1,10,20)
np.linspace(1,10,20,retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [16]:
# fourth method
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand()

0.42302624216662077

In [27]:
np.random.rand(3,3)

array([[0.06362927, 0.76281001, 0.12623081],
       [0.79508922, 0.71339855, 0.36231983],
       [0.52753811, 0.11830929, 0.00390202]])

In [28]:
# will create uniform distribution
np.random.random([3,4])

array([[0.88008222, 0.23065554, 0.59018041, 0.86183274],
       [0.96160118, 0.83341013, 0.61524916, 0.78731607],
       [0.54157859, 0.04537744, 0.26626289, 0.92683767]])

In [29]:
# standard normal distribution
np.random.randn(3,4)

array([[-0.99396898,  1.53133865, -1.28889081,  1.59204903],
       [ 1.21711061, -0.82913409, -1.83862811, -1.60041247],
       [-1.27225467,  1.55558186,  2.05511277,  0.7038127 ]])

In [34]:
# np.random.randint(10,20)
# np.random.randint(10,20,5)
np.random.randint(10,20,[5,5])

array([[15, 11, 19, 16, 18],
       [10, 15, 18, 19, 18],
       [10, 14, 19, 10, 14],
       [10, 12, 11, 18, 12],
       [10, 19, 10, 10, 15]])

In [35]:
arr_2 = np.random.randint(10,20,[5,5])

In [36]:
arr_2

array([[11, 11, 17, 12, 15],
       [17, 11, 15, 14, 11],
       [10, 13, 12, 10, 17],
       [19, 10, 13, 19, 19],
       [18, 18, 11, 12, 16]])

In [37]:
arr_2[0]

array([11, 11, 17, 12, 15])

In [38]:
arr_2[0][0]

11

In [39]:
arr_2[0:3]

array([[11, 11, 17, 12, 15],
       [17, 11, 15, 14, 11],
       [10, 13, 12, 10, 17]])

In [41]:
arr_2[0:3,0:3]

array([[11, 11, 17],
       [17, 11, 15],
       [10, 13, 12]])

In [42]:
arr_2[:,0:3]

array([[11, 11, 17],
       [17, 11, 15],
       [10, 13, 12],
       [19, 10, 13],
       [18, 18, 11]])

In [43]:
arr_2[:,[0,2,4]]

array([[11, 17, 15],
       [17, 15, 11],
       [10, 12, 17],
       [19, 13, 19],
       [18, 11, 16]])

In [44]:
arr_2.shape

(5, 5)

In [47]:
arr_3 = np.random.randint(10,30,15)

In [48]:
arr_3

array([18, 23, 26, 22, 29, 13, 24, 29, 22, 11, 29, 26, 29, 11, 14])

In [49]:
arr_3.max()

29

In [50]:
arr_3.min()

11

In [51]:
arr_3.argmax()

4

In [52]:
arr_3.argmin()

9

In [53]:
np.zeros_like(arr_2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])